// https://stackoverflow.com/questions/3217492/list-of-language-codes-in-yaml-or-json
var languages = [
    {"code":"ab","name":"Abkhaz","nativeName":"аҧсуа"},
    {"code":"aa","name":"Afar","nativeName":"Afaraf"},
    {"code":"af","name":"Afrikaans","nativeName":"Afrikaans"},
    {"code":"ak","name":"Akan","nativeName":"Akan"},
    {"code":"sq","name":"Albanian","nativeName":"Shqip"},
    {"code":"am","name":"Amharic","nativeName":"አማርኛ"},
    {"code":"ar","name":"Arabic","nativeName":"العربية"},
    {"code":"an","name":"Aragonese","nativeName":"Aragonés"},
    {"code":"hy","name":"Armenian","nativeName":"Հայերեն"},
    {"code":"as","name":"Assamese","nativeName":"অসমীয়া"},
    {"code":"av","name":"Avaric","nativeName":"авар мацӀ, магӀарул мацӀ"},
    {"code":"ae","name":"Avestan","nativeName":"avesta"},
    {"code":"ay","name":"Aymara","nativeName":"aymar aru"},
    {"code":"az","name":"Azerbaijani","nativeName":"azərbaycan dili"},
    {"code":"bm","name":"Bambara","nativeName":"bamanankan"},
    {"code":"ba","name":"Bashkir","nativeName":"башҡорт теле"},
    {"code":"eu","name":"Basque","nativeName":"euskara, euskera"},
    {"code":"be","name":"Belarusian","nativeName":"Беларуская"},
    {"code":"bn","name":"Bengali","nativeName":"বাংলা"},
    {"code":"bh","name":"Bihari","nativeName":"भोजपुरी"},
    {"code":"bi","name":"Bislama","nativeName":"Bislama"},
    {"code":"bs","name":"Bosnian","nativeName":"bosanski jezik"},
    {"code":"br","name":"Breton","nativeName":"brezhoneg"},
    {"code":"bg","name":"Bulgarian","nativeName":"български език"},
    {"code":"my","name":"Burmese","nativeName":"ဗမာစာ"},
    {"code":"ca","name":"Catalan; Valencian","nativeName":"Català"},
    {"code":"ch","name":"Chamorro","nativeName":"Chamoru"},
    {"code":"ce","name":"Chechen","nativeName":"нохчийн мотт"},
    {"code":"ny","name":"Chichewa; Chewa; Nyanja","nativeName":"chiCheŵa, chinyanja"},
    {"code":"zh","name":"Chinese","nativeName":"中文 (Zhōngwén), 汉语, 漢語"},
    {"code":"cv","name":"Chuvash","nativeName":"чӑваш чӗлхи"},
    {"code":"kw","name":"Cornish","nativeName":"Kernewek"},
    {"code":"co","name":"Corsican","nativeName":"corsu, lingua corsa"},
    {"code":"cr","name":"Cree","nativeName":"ᓀᐦᐃᔭᐍᐏᐣ"},
    {"code":"hr","name":"Croatian","nativeName":"hrvatski"},
    {"code":"cs","name":"Czech","nativeName":"česky, čeština"},
    {"code":"da","name":"Danish","nativeName":"dansk"},
    {"code":"dv","name":"Divehi; Dhivehi; Maldivian;","nativeName":"ދިވެހި"},
    {"code":"nl","name":"Dutch","nativeName":"Nederlands, Vlaams"},
    {"code":"en","name":"English","nativeName":"English"},
    {"code":"eo","name":"Esperanto","nativeName":"Esperanto"},
    {"code":"et","name":"Estonian","nativeName":"eesti, eesti keel"},
    {"code":"ee","name":"Ewe","nativeName":"Eʋegbe"},
    {"code":"fo","name":"Faroese","nativeName":"føroyskt"},
    {"code":"fj","name":"Fijian","nativeName":"vosa Vakaviti"},
    {"code":"fi","name":"Finnish","nativeName":"suomi, suomen kieli"},
    {"code":"fr","name":"French","nativeName":"français, langue française"},
    {"code":"ff","name":"Fula; Fulah; Pulaar; Pular","nativeName":"Fulfulde, Pulaar, Pular"},
    {"code":"gl","name":"Galician","nativeName":"Galego"},
    {"code":"ka","name":"Georgian","nativeName":"ქართული"},
    {"code":"de","name":"German","nativeName":"Deutsch"},
    {"code":"el","name":"Greek, Modern","nativeName":"Ελληνικά"},
    {"code":"gn","name":"Guaraní","nativeName":"Avañeẽ"},
    {"code":"gu","name":"Gujarati","nativeName":"ગુજરાતી"},
    {"code":"ht","name":"Haitian; Haitian Creole","nativeName":"Kreyòl ayisyen"},
    {"code":"ha","name":"Hausa","nativeName":"Hausa, هَوُسَ"},
    {"code":"he","name":"Hebrew (modern)","nativeName":"עברית"},
    {"code":"hz","name":"Herero","nativeName":"Otjiherero"},
    {"code":"hi","name":"Hindi","nativeName":"हिन्दी, हिंदी"},
    {"code":"ho","name":"Hiri Motu","nativeName":"Hiri Motu"},
    {"code":"hu","name":"Hungarian","nativeName":"Magyar"},
    {"code":"ia","name":"Interlingua","nativeName":"Interlingua"},
    {"code":"id","name":"Indonesian","nativeName":"Bahasa Indonesia"},
    {"code":"ie","name":"Interlingue","nativeName":"Originally called Occidental; then Interlingue after WWII"},
    {"code":"ga","name":"Irish","nativeName":"Gaeilge"},
    {"code":"ig","name":"Igbo","nativeName":"Asụsụ Igbo"},
    {"code":"ik","name":"Inupiaq","nativeName":"Iñupiaq, Iñupiatun"},
    {"code":"io","name":"Ido","nativeName":"Ido"},
    {"code":"is","name":"Icelandic","nativeName":"Íslenska"},
    {"code":"it","name":"Italian","nativeName":"Italiano"},
    {"code":"iu","name":"Inuktitut","nativeName":"ᐃᓄᒃᑎᑐᑦ"},
    {"code":"ja","name":"Japanese","nativeName":"日本語 (にほんご／にっぽんご)"},
    {"code":"jv","name":"Javanese","nativeName":"basa Jawa"},
    {"code":"kl","name":"Kalaallisut, Greenlandic","nativeName":"kalaallisut, kalaallit oqaasii"},
    {"code":"kn","name":"Kannada","nativeName":"ಕನ್ನಡ"},
    {"code":"kr","name":"Kanuri","nativeName":"Kanuri"},
    {"code":"ks","name":"Kashmiri","nativeName":"कश्मीरी, كشميري‎"},
    {"code":"kk","name":"Kazakh","nativeName":"Қазақ тілі"},
    {"code":"km","name":"Khmer","nativeName":"ភាសាខ្មែរ"},
    {"code":"ki","name":"Kikuyu, Gikuyu","nativeName":"Gĩkũyũ"},
    {"code":"rw","name":"Kinyarwanda","nativeName":"Ikinyarwanda"},
    {"code":"ky","name":"Kirghiz, Kyrgyz","nativeName":"кыргыз тили"},
    {"code":"kv","name":"Komi","nativeName":"коми кыв"},
    {"code":"kg","name":"Kongo","nativeName":"KiKongo"},
    {"code":"ko","name":"Korean","nativeName":"한국어 (韓國語), 조선말 (朝鮮語)"},
    {"code":"ku","name":"Kurdish","nativeName":"Kurdî, كوردی‎"},
    {"code":"kj","name":"Kwanyama, Kuanyama","nativeName":"Kuanyama"},
    {"code":"la","name":"Latin","nativeName":"latine, lingua latina"},
    {"code":"lb","name":"Luxembourgish, Letzeburgesch","nativeName":"Lëtzebuergesch"},
    {"code":"lg","name":"Luganda","nativeName":"Luganda"},
    {"code":"li","name":"Limburgish, Limburgan, Limburger","nativeName":"Limburgs"},
    {"code":"ln","name":"Lingala","nativeName":"Lingála"},
    {"code":"lo","name":"Lao","nativeName":"ພາສາລາວ"},
    {"code":"lt","name":"Lithuanian","nativeName":"lietuvių kalba"},
    {"code":"lu","name":"Luba-Katanga","nativeName":"Luba-Katanga"},
    {"code":"lv","name":"Latvian","nativeName":"latviešu valoda"},
    {"code":"gv","name":"Manx","nativeName":"Gaelg, Gailck"},
    {"code":"mk","name":"Macedonian","nativeName":"македонски јазик"},
    {"code":"mg","name":"Malagasy","nativeName":"Malagasy fiteny"},
    {"code":"ms","name":"Malay","nativeName":"bahasa Melayu, بهاس ملايو‎"},
    {"code":"ml","name":"Malayalam","nativeName":"മലയാളം"},
    {"code":"mt","name":"Maltese","nativeName":"Malti"},
    {"code":"mi","name":"Māori","nativeName":"te reo Māori"},
    {"code":"mr","name":"Marathi (Marāṭhī)","nativeName":"मराठी"},
    {"code":"mh","name":"Marshallese","nativeName":"Kajin M̧ajeļ"},
    {"code":"mn","name":"Mongolian","nativeName":"монгол"},
    {"code":"na","name":"Nauru","nativeName":"Ekakairũ Naoero"},
    {"code":"nv","name":"Navajo, Navaho","nativeName":"Diné bizaad, Dinékʼehǰí"},
    {"code":"nb","name":"Norwegian Bokmål","nativeName":"Norsk bokmål"},
    {"code":"nd","name":"North Ndebele","nativeName":"isiNdebele"},
    {"code":"ne","name":"Nepali","nativeName":"नेपाली"},
    {"code":"ng","name":"Ndonga","nativeName":"Owambo"},
    {"code":"nn","name":"Norwegian Nynorsk","nativeName":"Norsk nynorsk"},
    {"code":"no","name":"Norwegian","nativeName":"Norsk"},
    {"code":"ii","name":"Nuosu","nativeName":"ꆈꌠ꒿ Nuosuhxop"},
    {"code":"nr","name":"South Ndebele","nativeName":"isiNdebele"},
    {"code":"oc","name":"Occitan","nativeName":"Occitan"},
    {"code":"oj","name":"Ojibwe, Ojibwa","nativeName":"ᐊᓂᔑᓈᐯᒧᐎᓐ"},
    {"code":"cu","name":"Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic","nativeName":"ѩзыкъ словѣньскъ"},
    {"code":"om","name":"Oromo","nativeName":"Afaan Oromoo"},
    {"code":"or","name":"Oriya","nativeName":"ଓଡ଼ିଆ"},
    {"code":"os","name":"Ossetian, Ossetic","nativeName":"ирон æвзаг"},
    {"code":"pa","name":"Panjabi, Punjabi","nativeName":"ਪੰਜਾਬੀ, پنجابی‎"},
    {"code":"pi","name":"Pāli","nativeName":"पाऴि"},
    {"code":"fa","name":"Persian","nativeName":"فارسی"},
    {"code":"pl","name":"Polish","nativeName":"polski"},
    {"code":"ps","name":"Pashto, Pushto","nativeName":"پښتو"},
    {"code":"pt","name":"Portuguese","nativeName":"Português"},
    {"code":"qu","name":"Quechua","nativeName":"Runa Simi, Kichwa"},
    {"code":"rm","name":"Romansh","nativeName":"rumantsch grischun"},
    {"code":"rn","name":"Kirundi","nativeName":"kiRundi"},
    {"code":"ro","name":"Romanian, Moldavian, Moldovan","nativeName":"română"},
    {"code":"ru","name":"Russian","nativeName":"русский язык"},
    {"code":"sa","name":"Sanskrit (Saṁskṛta)","nativeName":"संस्कृतम्"},
    {"code":"sc","name":"Sardinian","nativeName":"sardu"},
    {"code":"sd","name":"Sindhi","nativeName":"सिन्धी, سنڌي، سندھی‎"},
    {"code":"se","name":"Northern Sami","nativeName":"Davvisámegiella"},
    {"code":"sm","name":"Samoan","nativeName":"gagana faa Samoa"},
    {"code":"sg","name":"Sango","nativeName":"yângâ tî sängö"},
    {"code":"sr","name":"Serbian","nativeName":"српски језик"},
    {"code":"gd","name":"Scottish Gaelic; Gaelic","nativeName":"Gàidhlig"},
    {"code":"sn","name":"Shona","nativeName":"chiShona"},
    {"code":"si","name":"Sinhala, Sinhalese","nativeName":"සිංහල"},
    {"code":"sk","name":"Slovak","nativeName":"slovenčina"},
    {"code":"sl","name":"Slovene","nativeName":"slovenščina"},
    {"code":"so","name":"Somali","nativeName":"Soomaaliga, af Soomaali"},
    {"code":"st","name":"Southern Sotho","nativeName":"Sesotho"},
    {"code":"es","name":"Spanish; Castilian","nativeName":"español, castellano"},
    {"code":"su","name":"Sundanese","nativeName":"Basa Sunda"},
    {"code":"sw","name":"Swahili","nativeName":"Kiswahili"},
    {"code":"ss","name":"Swati","nativeName":"SiSwati"},
    {"code":"sv","name":"Swedish","nativeName":"svenska"},
    {"code":"ta","name":"Tamil","nativeName":"தமிழ்"},
    {"code":"te","name":"Telugu","nativeName":"తెలుగు"},
    {"code":"tg","name":"Tajik","nativeName":"тоҷикӣ, toğikī, تاجیکی‎"},
    {"code":"th","name":"Thai","nativeName":"ไทย"},
    {"code":"ti","name":"Tigrinya","nativeName":"ትግርኛ"},
    {"code":"bo","name":"Tibetan Standard, Tibetan, Central","nativeName":"བོད་ཡིག"},
    {"code":"tk","name":"Turkmen","nativeName":"Türkmen, Түркмен"},
    {"code":"tl","name":"Tagalog","nativeName":"Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔"},
    {"code":"tn","name":"Tswana","nativeName":"Setswana"},
    {"code":"to","name":"Tonga (Tonga Islands)","nativeName":"faka Tonga"},
    {"code":"tr","name":"Turkish","nativeName":"Türkçe"},
    {"code":"ts","name":"Tsonga","nativeName":"Xitsonga"},
    {"code":"tt","name":"Tatar","nativeName":"татарча, tatarça, تاتارچا‎"},
    {"code":"tw","name":"Twi","nativeName":"Twi"},
    {"code":"ty","name":"Tahitian","nativeName":"Reo Tahiti"},
    {"code":"ug","name":"Uighur, Uyghur","nativeName":"Uyƣurqə, ئۇيغۇرچە‎"},
    {"code":"uk","name":"Ukrainian","nativeName":"українська"},
    {"code":"ur","name":"Urdu","nativeName":"اردو"},
    {"code":"uz","name":"Uzbek","nativeName":"zbek, Ўзбек, أۇزبېك‎"},
    {"code":"ve","name":"Venda","nativeName":"Tshivenḓa"},
    {"code":"vi","name":"Vietnamese","nativeName":"Tiếng Việt"},
    {"code":"vo","name":"Volapük","nativeName":"Volapük"},
    {"code":"wa","name":"Walloon","nativeName":"Walon"},
    {"code":"cy","name":"Welsh","nativeName":"Cymraeg"},
    {"code":"wo","name":"Wolof","nativeName":"Wollof"},
    {"code":"fy","name":"Western Frisian","nativeName":"Frysk"},
    {"code":"xh","name":"Xhosa","nativeName":"isiXhosa"},
    {"code":"yi","name":"Yiddish","nativeName":"ייִדיש"},
    {"code":"yo","name":"Yoruba","nativeName":"Yorùbá"},
    {"code":"za","name":"Zhuang, Chuang","nativeName":"Saɯ cueŋƅ, Saw cuengh"}
]

var regions = [
    {"name":"Africa", "countries": [
        {"code":"ar_DZ","name":"Algeria","nativeName":"الجزائر"},
        {"code":"pt_AO","name":"Angola","nativeName":"Angola"},
        {"code":"fr_BJ","name":"Benin","nativeName":"Bénin"},
        {"code":"en_BW","name":"Botswana","nativeName":"Botswana"},
        {"code":"fr_BF","name":"Burkina Faso","nativeName":"Burkina Faso"},
        {"code":"rn_BI","name":"Burundi","nativeName":"Uburundi"},
        {"code":"fr_CM","name":"Cameroon","nativeName":"Cameroun"},
        {"code":"pt_CV","name":"Cape Verde","nativeName":"Cabo Verde"},
        {"code":"fr_CF","name":"Central African Republic","nativeName":"République centrafricaine"},
        {"code":"es_EA","name":"Ceuta And Melilla","nativeName":"Ceuta y Melilla"},
        {"code":"fr_TD","name":"Chad","nativeName":"Tchad"},
        {"code":"ar_KM","name":"Comoros","nativeName":"جزر القمر"},
        {"code":"sw_CD","name":"Congo Kinshasa","nativeName":"Jamhuri ya Kidemokrasia ya Kongo"},
        {"code":"fr_CG","name":"Congo Brazzaville","nativeName":"Congo-Brazzaville"},
        {"code":"fr_CI","name":"Ivory Coast","nativeName":"Côte d’Ivoire"},
        {"code":"ar_EG","name":"Egypt","nativeName":"مصر"},
        {"code":"es_GQ","name":"Equatorial Guinea","nativeName":"Guinea Ecuatorial"},
        {"code":"ti_ER","name":"Eritrea","nativeName":"ኤርትራ"},
        {"code":"am_ET","name":"Ethiopia","nativeName":"ኢትዮጵያ"},
        {"code":"fr_GA","name":"Gabon","nativeName":"Gabon"},
        {"code":"en_GM","name":"Gambia","nativeName":"Gambia"},
        {"code":"ak_GH","name":"Ghana","nativeName":"Gaana"},
        {"code":"fr_GN","name":"Guinea","nativeName":"Guinée"},
        {"code":"pt_GW","name":"Guinea Bissau","nativeName":"Guiné-Bissau"},
        {"code":"sw_KE","name":"Kenya","nativeName":"Kenya"},
        {"code":"en_LS","name":"Lesotho","nativeName":"Lesotho"},
        {"code":"en_LR","name":"Liberia","nativeName":"Liberia"},
        {"code":"ar_LY","name":"Libya","nativeName":"ليبيا"},
        {"code":"mg_MG","name":"Madagascar","nativeName":"Madagasikara"},
        {"code":"ar_MR","name":"Mauritania","nativeName":"موريتانيا"},
        {"code":"fr_YT","name":"Mayotte","nativeName":"Mayotte"},
        {"code":"ar_MA","name":"Morocco","nativeName":"المغرب"},
        {"code":"pt_MZ","name":"Mozambique","nativeName":"Moçambique"},
        {"code":"en_MW","name":"Malawi","nativeName":"Malawi"},
        {"code":"bm_ML","name":"Mali","nativeName":"Mali"},
        {"code":"mfe_MU","name":"Mauritius","nativeName":"Moris"},
        {"code":"af_NA","name":"Namibia","nativeName":"Namibië"},
        {"code":"ha_NE","name":"Niger","nativeName":"Nijar"},
        {"code":"en_NG","name":"Nigeria","nativeName":"Nigeria"},
        {"code":"fr_RE","name":"Reunion","nativeName":"La Réunion"},
        {"code":"rw_RW","name":"Rwanda","nativeName":"U Rwanda"},
        {"code":"en_SH","name":"Saint Helena","nativeName":"St. Helena"},
        {"code":"pt_ST","name":"Sao Tome And Principe","nativeName":"São Tomé e Príncipe"},
        {"code":"fr_SN","name":"Senegal","nativeName":"Sénégal"},
        {"code":"fr_SC","name":"Seychelles","nativeName":"Seychelles"},
        {"code":"en_SL","name":"Sierra Leone","nativeName":"Sierra Leone"},
        {"code":"so_SO","name":"Somalia","nativeName":"Soomaaliya"},
        {"code":"en_SS","name":"South Sudan","nativeName":"South Sudan"},
        {"code":"en_ZA","name":"South Africa","nativeName":"South Africa"},
        {"code":"ar_SD","name":"Sudan","nativeName":"السودان"},
        {"code":"en_SZ","name":"Swaziland","nativeName":"Swaziland"},
        {"code":"sw_TZ","name":"Tanzania","nativeName":"Tanzania"},
        {"code":"fr_TG","name":"Togo","nativeName":"Togo"},
        {"code":"ar_TN","name":"Tunisia","nativeName":"تونس"},
        {"code":"sw_UG","name":"Uganda","nativeName":"Uganda"},
        {"code":"ar_EH","name":"Western Sahara","nativeName":"الصحراء الغربي)"},
        {"code":"en_ZM","name":"Zambia","nativeName":"Zambia"},
        {"code":"sn_ZW","name":"Zimbabwe","nativeName":"Zimbabwe"}
    ]},
    {"name":"Asia", "countries": [
        {"code":"fa_AF","name":"Afghanistan","nativeName":"افغانستان"},
        {"code":"hy_AM","name":"Armenia","nativeName":"Հայա}տան"},
        {"code":"az_AZ","name":"Azerbaijan","nativeName":"Azərbaycan"},
        {"code":"ar_BH","name":"Bahrain","nativeName":"البحرين"},
        {"code":"bn_BD","name":"Bangladesh","nativeName":"বাংলাদেশ"},
        {"code":"dz_BT","name":"Bhutan","nativeName":"འབྲུག"},
        {"code":"en_IO","name":"British Indian Ocean Territory","nativeName":"British Indian Ocean Territory"},
        {"code":"ms_BN","name":"Brunei","nativeName":"Brunei"},
        {"code":"km_KH","name":"Cambodia","nativeName":"កម្ពុជា"},
        {"code":"zh_CN","name":"China","nativeName":"中国"},
        {"code":"en_CX","name":"Christmas Island","nativeName":"Christmas Island"},
        {"code":"en_CC","name":"Cocos Islands","nativeName":"Cocos (Keeling) Islands"},
        {"code":"en_DG","name":"Diego Garcia","nativeName":"Diego Garcia"},
        {"code":"ka_GE","name":"Georgia","nativeName":"საქართველო"},
        {"code":"zh_HK","name":"Hong Kong","nativeName":"中國香港特別行政區"},
        {"code":"ar_AE","name":"United Arab Emirates","nativeName":"الإمارات العربي) المتحد)"},
        {"code":"hi_IN","name":"India","nativeName":"भारत"},
        {"code":"id_ID","name":"Indonesia","nativeName":"Indonesia"},
        {"code":"fa_IR","name":"Iran","nativeName":"ایران"},
        {"code":"ar_IQ","name":"Iraq","nativeName":"العراق"},
        {"code":"he_IL","name":"Israel","nativeName":"ישראל"},
        {"code":"ja_JP","name":"Japan","nativeName":"日本"},
        {"code":"ar_JO","name":"Jordan","nativeName":"الأردن"},
        {"code":"ru_KZ","name":"Kazakhstan","nativeName":"Казахстан"},
        {"code":"ko_KP","name":"North Korea","nativeName":"조선민주주의인민공화국"},
        {"code":"ko_KR","name":"South Korea","nativeName":"대한민국"},
        {"code":"ar_KW","name":"Kuwait","nativeName":"الكويت"},
        {"code":"ky_KG","name":"Kyrgyzstan","nativeName":"Кыргызстан"},
        {"code":"lo_LA","name":"Laos","nativeName":"ລາວ"},
        {"code":"ar_LB","name":"Lebanon","nativeName":"لبنان"},
        {"code":"zh_MO","name":"Macau","nativeName":"中國澳門特別行政區"},
        {"code":"ms_MY","name":"Malaysia","nativeName":"Malaysia"},
        {"code":"dv_MV","name":"Maldives","nativeName":"Maldives"},
        {"code":"mn_MN","name":"Mongolia","nativeName":"Монгол"},
        {"code":"my_MM","name":"Myanmar","nativeName":"မြန်မာ"},
        {"code":"ne_NP","name":"Nepal","nativeName":"नेपाल"},
        {"code":"ar_OM","name":"Oman","nativeName":"عُمان"},
        {"code":"ur_PK","name":"Pakistan","nativeName":"پاکستان"},
        {"code":"ar_PS","name":"Palestinian Territories","nativeName":"الأراضي الفلسطيني)"},
        {"code":"fil_PH","name":"Philippines","nativeName":"Pilipinas"},
        {"code":"ar_QA","name":"Qatar","nativeName":"قطر"},
        {"code":"ar_SA","name":"Saudi Arabia","nativeName":"المملك) العربي) السعودي)"},
        {"code":"en_SG","name":"Singapore","nativeName":"Singapore"},
        {"code":"si_LK","name":"Sri Lanka","nativeName":"ශ්u200Dරී ලංකාව"},
        {"code":"ar_SY","name":"Syria","nativeName":"سوريا"},
        {"code":"zh_TW","name":"Taiwan","nativeName":"台灣"},
        {"code":"tg_TJ","name":"Tajikistan","nativeName":"Тоҷикистон"},
        {"code":"th_TH","name":"Thailand","nativeName":"ไทย"},
        {"code":"tr_TR","name":"Turkey","nativeName":"Türkiye"},
        {"code":"tk_TM","name":"Turkmenistan","nativeName":"Türkmenistan"},
        {"code":"uz_UZ","name":"Uzbekistan","nativeName":"Oʻzbekiston"},
        {"code":"vi_VN","name":"Vietnam","nativeName":"Việt Nam"},
        {"code":"ar_YE","name":"Yemen","nativeName":"اليمن"}
    ]},
    {"name":"Europe", "countries": [
        {"code":"sv_AX","name":"Aland Islands","nativeName":"Åland"},
        {"code":"sq_AL","name":"Albania","nativeName":"Shqipëri"},
        {"code":"ca_AD","name":"Andorra","nativeName":"Andorra"},
        {"code":"de_AT","name":"Austria","nativeName":"Österreich"},
        {"code":"be_BY","name":"Belarus","nativeName":"Беларусь"},
        {"code":"nl_BE","name":"Belgium","nativeName":"België"},
        {"code":"bs_BA","name":"Bosnia And Herzegowina","nativeName":"Bosna i Hercegovina"},
        {"code":"bg_BG","name":"Bulgaria","nativeName":"България"},
        {"code":"es_IC","name":"Canary Islands","nativeName":"Canarias"},
        {"code":"hr_HR","name":"Croatia","nativeName":"Hrvatska"},
        {"code":"el_CY","name":"Cyprus","nativeName":"Κύπρος"},
        {"code":"cs_CZ","name":"Czech Republic","nativeName":"Česko"},
        {"code":"da_DK","name":"Denmark","nativeName":"Danmark"},
        {"code":"et_EE","name":"Estonia","nativeName":"Eesti"},
        {"code":"fo_FO","name":"Faroe Islands","nativeName":"Føroyar"},
        {"code":"fi_FI","name":"Finland","nativeName":"Suomi"},
        {"code":"fr_FR","name":"France","nativeName":"France"},
        {"code":"en_GG","name":"Guernsey","nativeName":"Guernsey"},
        {"code":"de_DE","name":"Germany","nativeName":"Deutschland"},
        {"code":"en_GI","name":"Gibraltar","nativeName":"Gibraltar"},
        {"code":"el_GR","name":"Greece","nativeName":"Ελλάδα"},
        {"code":"hu_HU","name":"Hungary","nativeName":"Magyarország"},
        {"code":"is_IS","name":"Iceland","nativeName":"Ísland"},
        {"code":"en_IE","name":"Ireland","nativeName":"Ireland"},
        {"code":"en_IM","name":"Isle Of Man","nativeName":"Isle of Man"},
        {"code":"it_IT","name":"Italy","nativeName":"Italia"},
        {"code":"en_JE","name":"Jersey","nativeName":"Jersey"},
        {"code":"lv_LV","name":"Latvia","nativeName":"Latvija"},
        {"code":"de_LI","name":"Liechtenstein","nativeName":"Liechtenstein"},
        {"code":"lt_LT","name":"Lithuania","nativeName":"Lietuva"},
        {"code":"fr_LU","name":"Luxembourg","nativeName":"Luxembourg"},
        {"code":"mk_MK","name":"Macedonia","nativeName":"Македонија"},
        {"code":"mt_MT","name":"Malta","nativeName":"Malta"},
        {"code":"ro_MD","name":"Moldova","nativeName":"Republica Moldova"},
        {"code":"fr_MC","name":"Monaco","nativeName":"Monaco"},
        {"code":"sr_ME","name":"Montenegro","nativeName":"Crna Gora"},
        {"code":"nl_NL","name":"Netherlands","nativeName":"Nederland"},
        {"code":"nb_NO","name":"Norway","nativeName":"Norge"},
        {"code":"pl_PL","name":"Poland","nativeName":"Polska"},
        {"code":"pt_PT","name":"Portugal","nativeName":"Portugal"},
        {"code":"ro_RO","name":"Romania","nativeName":"România"},
        {"code":"ru_RU","name":"Russia","nativeName":"Россия"},
        {"code":"it_SM","name":"San Marino","nativeName":"San Marino"},
        {"code":"sr_RS","name":"Serbia","nativeName":"Србија"},
        {"code":"sk_SK","name":"Slovakia","nativeName":"Slovensko"},
        {"code":"sl_SI","name":"Slovenia","nativeName":"Slovenija"},
        {"code":"es_ES","name":"Spain","nativeName":"España"},
        {"code":"sv_SE","name":"Sweden","nativeName":"Sverige"},
        {"code":"de_CH","name":"Switzerland","nativeName":"Schweiz"},
        {"code":"nb_SJ","name":"Svalbard And Jan Mayen Islands","nativeName":"Svalbard og Jan Mayen"},
        {"code":"uk_UA","name":"Ukraine","nativeName":"Україна"},
        {"code":"en_GB","name":"United Kingdom","nativeName":"United Kingdom"},
        {"code":"it_VA","name":"Vatican City State","nativeName":"Città del Vaticano"}
    ]},
    {"name":"North America", "countries": [
        {"code":"en_AI","name":"Anguilla","nativeName":"Anguilla"},
        {"code":"en_AG","name":"Antigua And Barbuda","nativeName":"Antigua And Barbuda"},
        {"code":"nl_AW","name":"Aruba","nativeName":"Aruba"},
        {"code":"en_BS","name":"Bahamas","nativeName":"Bahamas"},
        {"code":"en_BB","name":"Barbados","nativeName":"Barbados"},
        {"code":"en_BZ","name":"Belize","nativeName":"Belize"},
        {"code":"en_BM","name":"Bermuda","nativeName":"Bermuda"},
        {"code":"en_VG","name":"British Virgin Islands","nativeName":"British Virgin Islands"},
        {"code":"en_CA","name":"Canada","nativeName":"Canada"},
        {"code":"en_KY","name":"Cayman Islands","nativeName":"Cayman Islands"},
        {"code":"es_CR","name":"Costa Rica","nativeName":"Costa Rica"},
        {"code":"es_CU","name":"Cuba","nativeName":"Cuba"},
        {"code":"en_DM","name":"Dominica","nativeName":"Dominica"},
        {"code":"es_DO","name":"Dominican Republic","nativeName":"República Dominicana"},
        {"code":"es_SV","name":"El Salvador","nativeName":"El Salvador"},
        {"code":"kl_GL","name":"Greenland","nativeName":"Kalaallit Nunaat"},
        {"code":"en_GD","name":"Grenada","nativeName":"Grenada"},
        {"code":"fr_GP","name":"Guadeloupe","nativeName":"Guadeloupe"},
        {"code":"es_GT","name":"Guatemala","nativeName":"Guatemala"},
        {"code":"es_HN","name":"Honduras","nativeName":"Honduras"},
        {"code":"en_JM","name":"Jamaica","nativeName":"Jamaica"},
        {"code":"fr_MQ","name":"Martinique","nativeName":"Martinique"},
        {"code":"es_MX","name":"Mexico","nativeName":"México"},
        {"code":"en_MS","name":"Montserrat","nativeName":"Montserrat"},
        {"code":"es_NI","name":"Nicaragua","nativeName":"Nicaragua"},
        {"code":"es_PA","name":"Panama","nativeName":"Panamá"},
        {"code":"es_PR","name":"Puerto Rico","nativeName":"Puerto Rico"},
        {"code":"fr_BL","name":"Saint Barthelemy","nativeName":"Saint-Barthélemy"},
        {"code":"en_KN","name":"Saint Kitts And Nevis","nativeName":"Saint Kitts And Nevis"},
        {"code":"en_LC","name":"Saint Lucia","nativeName":"St. Lucia"},
        {"code":"fr_MF","name":"Saint Martin","nativeName":"Saint-Martin"},
        {"code":"fr_PM","name":"Saint Pierre And Miquelon","nativeName":"Saint-Pierre-et-Miquelon"},
        {"code":"en_VC","name":"Saint Vincent And The Grenadines","nativeName":"Saint Vincent And The Grenadines"},
        {"code":"en_TT","name":"Trinidad And Tobago","nativeName":"Trinidad And Tobago"},
        {"code":"en_TC","name":"Turks And Caicos Islands","nativeName":"Turks And Caicos Islands"},
        {"code":"en_US","name":"United States","nativeName":"United States"},
        {"code":"en_VI","name":"U.S. Virgin Islands","nativeName":"U.S. Virgin Islands"},
    ]},
    {"name":"Oceania", "countries": [
        {"code":"en_AS","name":"American Samoa","nativeName":"American Samoa"},
        {"code":"en_AU","name":"Australia","nativeName":"Australia"},
        {"code":"en_CK","name":"Cook Islands","nativeName":"Cook Islands"},
        {"code":"pt_TL","name":"East Timor","nativeName":"Timor-Leste"},
        {"code":"en_FJ","name":"Fiji","nativeName":"Fiji"},
        {"code":"fr_PF","name":"French Polynesia","nativeName":"Polynésie française"},
        {"code":"en_GU","name":"Guam","nativeName":"Guam"},
        {"code":"en_KI","name":"Kiribati","nativeName":"Kiribati"},
        {"code":"en_MH","name":"Marshall Islands","nativeName":"Marshall Islands"},
        {"code":"en_FM","name":"Micronesia","nativeName":"Micronesia"},
        {"code":"en_NR","name":"Nauru","nativeName":"Nauru"},
        {"code":"fr_NC","name":"New Caledonia","nativeName":"Nouvelle-Calédonie"},
        {"code":"en_NZ","name":"New Zealand","nativeName":"New Zealand"},
        {"code":"en_NU","name":"Niue","nativeName":"Niue"},
        {"code":"en_NF","name":"Norfolk Island","nativeName":"Norfolk Island"},
        {"code":"en_MP","name":"Northern Mariana Islands","nativeName":"Northern Mariana Islands"},
        {"code":"en_PW","name":"Palau","nativeName":"Palau"},
        {"code":"en_PG","name":"Papua New Guinea","nativeName":"Papua New Guinea"},
        {"code":"en_PN","name":"Pitcairn","nativeName":"Pitcairn Islands"},
        {"code":"en_WS","name":"Samoa","nativeName":"Samoa"},
        {"code":"en_SB","name":"Solomon Islands","nativeName":"Solomon Islands"},
        {"code":"en_TK","name":"Tokelau","nativeName":"Tokelau"},
        {"code":"to_TO","name":"Tonga","nativeName":"Tonga"},
        {"code":"en_TV","name":"Tuvalu","nativeName":"Tuvalu"},
        {"code":"en_UM","name":"U.S. Outlying Islands","nativeName":"U.S. Outlying Islands"},
        {"code":"en_VU","name":"Vanuatu","nativeName":"Vanuatu"},
        {"code":"fr_WF","name":"Wallis And Futuna Islands","nativeName":"Wallis-et-Futuna"}
    ]},
    {"name":"South America", "countries": [
        {"code":"es_AR","name":"Argentina","nativeName":"Argentina"},
        {"code":"es_BO","name":"Bolivia","nativeName":"Bolivia"},
        {"code":"pt_BR","name":"Brazil","nativeName":"Brasil"},
        {"code":"es_CL","name":"Chile","nativeName":"Chile"},
        {"code":"es_CO","name":"Colombia","nativeName":"Colombia"},
        {"code":"es_EC","name":"Ecuador","nativeName":"Ecuador"},
        {"code":"en_FK","name":"Falkland Islands","nativeName":"Falkland Islands"},
        {"code":"fr_GF","name":"French Guiana","nativeName":"Guyane française"},
        {"code":"en_GY","name":"Guyana","nativeName":"Guyana"},
        {"code":"gn_PY","name":"Paraguay","nativeName":"Paraguay"},
        {"code":"es_PE","name":"Peru","nativeName":"Perú"},
        {"code":"nl_SR","name":"Suriname","nativeName":"Suriname"},
        {"code":"es_UY","name":"Uruguay","nativeName":"Uruguay"},
        {"code":"es_VE","name":"Venezuela","nativeName":"Venezuela"}
    ]}
]

function getLanguageFromCode(code)
{
    var name;
    var nativeName;

    for (var i = 0; i < languages.length; ++i) {
        if (languages[i].code === code) {
            name = languages[i].name;
            nativeName = languages[i].nativeName;

            if (name !== nativeName) {
                name = nativeName + " (" + name + ")";
            }

            break;
        }
    }

    return name;
}

function getCountryFromCode(code, name)
{
    for (var i = 0; i < regions.length; ++i) {
        var countries = regions[i].countries;
        for (var j = 0; j < countries.length; ++j) {
            if (countries[j].code === code) {
                if (name === "native")
                    return countries[j].nativeName;
                else
                    return countries[j].name;
            }
        }
    }

    return "";
}
